---
- name: To execute the SSO LOAD TEST
  hosts: all
  tasks:
    - name: Copy the file from my PC to cluster
      copy:
        src: /Users/stethoma/ansible-work/keycloak/testsuite/performance/tests/target/provisioned-system.properties
        dest: /home/centos/keycloak/testsuite/performance/tests/target/provisioned-system.properties
        owner: centos
        group: centos
        mode: '0764'

    - name: execute the commands
      command: "{{ item }}"
      become: yes
      become_user: centos
      with_items: 
        - cd keycloak/testsuite/performance
        - mvn clean install
        - mvn verify -Pgenerate-data -Ddataset=1r_10c_100u -DnumOfWorkers=10
        - export WARMUP_PERIOD=900
        - export RAMPUP_PERIOD=10
        - export MEASUREMENT_PERIOD=900
        - export STRESS_TEST_MAX_ITERATIONS=1
        - ./stress-test.sh -DmaxMeanResponseTime=1000
      register: reg_out

    - name: Display the output
      debug: 
        msg: ”{{ reg_out.results | map (attribute=’stdout_lines’) | list }}”
      
